service: serverless-modern-slavery-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, self:custom.region}
  stage: ${opt:stage, self:custom.stage}
  profile: ${opt:profile}
  deploymentBucket: ${opt:deploymentBucket}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/modernSlaveryPredictions
    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::nuk-tnl-editorial-prod-staticassets

custom:
  region: eu-west-1
  stage: dev

functions:
  store:
    handler: handler.store
    timeout: 10
    events:
      - http:
          method: post
          path: store
          cors: true

  process:
    handler: handler.process
    timeout: 300
    events:
      - schedule: cron(0/30 * * * ? *)
      - http:
          method: get
          path: process
          cors: true

plugins:
  - serverless-offline

resources:
  Resources:
    offsideOrNot:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: modernSlaveryPredictions
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
